spring:
  profiles:
  active: dev
---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: springcloud-config-eureka
  #eureka配置
eureka:
  instance:
    hostname: eureka1 #eureka服务端的实例名称

  client:
    register-with-eureka: false #表示是否想eureka注册中心注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url: #监控页面
      # 单机：       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群：       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka2:7002/eureka/,http://eureka3:7003/eureka/


---
server:
  port: 7001
spring:
  profiles: test
  application:
    name:springcloud-config-eureka  

  #eureka配置
eureka:
  instance:
    hostname: eureka1 #eureka服务端的实例名称

  client:
    register-with-eureka: false #表示是否想eureka注册中心注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url: #监控页面
      # 单机：       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群：       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
